title: a blog
domain: acekyken.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://acekyken.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /blog      # place folder name if the site is served in a subfolder
theme: jekyll-theme-minimal

markdown: kramdown
paginate: 5
exclude:
  - Gemfile
  - Gemfile.lock
